apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: got-app
  name: got-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: got-app
  template:
    metadata:
      labels:
        app: got-app
    spec:
      containers:
        - image: ghcr.io/is2ac/got-deployment-k8s-gitops:0c2c13f
          name: got-app
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
