apiVersion: v1
kind: Service
metadata:
  labels:
    app: got-app
  name: got-app
spec:
  selector:
    app: got-app
  type: NodePort
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 5000


